@startuml
title Регистрация в Time

actor User
participant "[[/architect/components/applications.time Time]]" as Time
database "[[/architect/components/db.cabinet Cabinet]]" as Cabinet

User -> Time ++ : Ввод и отправка пароля
activate User
Time -> Cabinet ++ : Запрос аккаунта
return (результат)
Time -> Time : Валидация данных аккаунта и проверка пароля

group Пользователь найден
    alt Аккаунт валиден и пароль НЕ подходит
        User <-- Time : (Информация по восстановлению пароля)
    else Аккаунт НЕ валиден
        User <-- Time : (ошибка)
    end
end

group Включена фича strong-password-validation
    alt Пароль НЕ удовлетворяет требованиям
        User <-- Time : (ошибка)
    end
end

Time -> Time : Регистрация пользователя
return (результат)
deactivate User

@enduml