@startuml

actor User
participant Time
database Cabinet
participant Passport
database Passport as dbPassport

User -> Time ++ : Ввод и отправка логина
activate User
alt Фича automatic-redirect-to-sso ВКЛЮЧЕНА
User <-- Time : Переадресация на домен пользователя
else Фича automatic-redirect-to-sso ВЫКЛЮЧЕНА
return (Отображение формы для ввода пароля)
end alt
User -> Time ++ : Ввод и отправка пароля
Time -> Cabinet ++ : Запрос аккаунта
return (результат)
Time -> Time : Хеширование пароля
Time -> Time : Валидация данных аккаунта
alt Валидация пройдена
User <-- Time : (результат)
else Валидация НЕ пройдена
return (ошибка)
end alt


deactivate User
@enduml