@startuml
title Вход с помощью SSO в Time

actor User
participant "[[/architect/components/applications.time Time]]" as Time

User -> Time ++ : Открытие Time на поддомене компании пользователя
activate User
alt Пользователь НЕ находится в своей корпоративной сети
User <-- Time : Переадресация на сайт SSO клиента
end alt
Time -> Time : Авторизация пользователя
return (результат)

deactivate User

@enduml