@startuml
'https://plantuml.com/sequence-diagram

actor User
participant "[[/architect/components/applications.time Time]]" as Time
database "[[/architect/components/db.cabinet Cabinet DB]]" as Cabinet
participant "[[/architect/components/services.propertyfx PropertyFx Service]]" as PropertyFx
participant "[[/architect/components/services.budgeting Budgeting Service]]" as Budgeting
participant "[[/architect/components/services.authfx AuthFx Service]]" as AuthFx
queue Queue


activate User

User -> Time ++ : Переход к заполнению ДД и расходов
group Включена фича trip-expenses
    Time -> Cabinet ++ : Получение типов расходов
    return (результат)
end
Time -> PropertyFx ++ : Получение ДД командировки
return (результат)
group Включена фича company-grade-by-customproperties-journeys-only
    Time -> Time : Удаление ДД "Грейд сотрудника" (EmployeeLevel)
end
return (результат)
loop
User -> Time ++ : Выбор ДД
Time -> PropertyFx ++ : Получение зависимых ДД
return (результат)
return (результат)
end
loop
    User -> Time ++ : Добавление расхода
    return (результат)
end

opt Добавление суточных
    User -> Time ++ : Добавление суточных
    alt Настроен расчет суточных по доп. параметрам
    Time -> Budgeting ++ : Запрос параметров суточных
    return (результат)
    return (результат)
    User -> Time ++ : Выбор параметров суточных
    return (результат)
    User -> Time ++ : Расчет суточных
    end
    Time -> Budgeting ++ : Запрос суммы суточных
    return (результат)
    return (результат)
end

User -> Time ++ : Завершение создания командировки
Time -> PropertyFx ++ : Запись ДД
group Включена фича company-grade-by-customproperties-journeys-only
    Time -> Time : Добавление ДД "Цель поедки" (purpose_of_trip)\nкак "Грейд сотрудника" (EmployeeLevel)
end
return (результат)
Time -> Cabinet ++ : Запись расходов
return (результат)
group Активация командировки
Time -> AuthFx ++ : Проерка на необходимось авторизации командировки
return (результат)
Time -> Cabinet ++ : Активация командировки
Time -> Time : Запись статусов командировки
alt Авторизация факта поездки НЕ требуется
Time -> Queue : Отправка сообщения [[/architect/contexts/applications.time.messages.BusinessTripNotRequiredAssertionMessage BusinessTripNotRequiredAssertionMessage]]
end
return (результат)

return (страница командировки)

deactivate User
@enduml

