@startuml
'https://plantuml.com/sequence-diagram

skinparam MaxMessageSize 250

actor User
participant "[[/architect/components/applications.time Time]]" as Time
participant "[[/architect/components/services.propertyfx PropertyFx\nService]]" as PropertyFx
participant "[[/architect/components/services.vault Acis\n(vault)]]" as Acis
participant "[[/architect/components/services.pricingscheme PricingScheme\nService]]" as PricingScheme
participant "[[/architect/components/services.businesstrips BusinessTrips\nService]]" as BusinessTrips
database "[[/architect/components/db.cabinet CabinetDB]]" as Cabinet
database "[[/architect/components/db.profiles ProfilesDB]]" as Profiles
database "[[/architect/components/db.companies CompaniesDB]]" as Companies

activate User

loop
    User -> Time ++ : Поиск путешественника
    Time -> Profiles ++ : Запрос сотрудников
    return (результат)
    Time -> PropertyFx ++ : Получение табельных номер и департаментов
    return (результат)
    return (список сотрудников)
    User -> Time ++ : Добавление путешественника в список
    return (результат)
end
loop
    User -> Time ++ : Подтверждение списка путешественников
    Time -> Cabinet ++ : Получение настроек обслуживания и прав пользователя
    return (результат)
    Time -> Companies ++ : Получение компаний холдинга пользователя согласно настройкам обслуживания и правам пользователя
    return (результат)
    group Включена фича set_paymentcompany_from_profilecompany
        Time -> Time : Компания, выбранная в профиле указывается предвыбранной для путешественника
    end
    group Включена фича business-trip-requisites-company-from-customproperties
        Time -> PropertyFx ++ : Получение только компаний, для которых заполнены и валидны ДД сотрудника
        return (результат)
    end
    Time -> PricingScheme ++ : Получение форм оплат, доступных пользователю для выбранной компании
    return (результат)
    Time -> Acis ++ : Получение доступных карт
    return (результат)
    group Включена фича company-form-of-payments-override-enabled
        Time -> Companies ++ : Переопределение форм оплат???
        return (результат)
        Time -> Acis ++ : Получаем и оставляем только карты, доступные сотруднику
        return (результат)
    end
    group Включена фича trip-only-profile-personal-bankCard-payment-method
        Time -> Acis ++ : Получаем и оставляем только карты, доступные сотруднику
        return (результат)
    end
    group Включена фича profile-personal-bankCard-and-other-payment-method
        Time -> Acis ++ : Получаем и оставляем только карты, доступные сотруднику
        return (результат)
        Time -> Companies ++ : Добавляем остальные формы оплаты, доступные сотруднику
        return (результат)
    end
    return (результат)
end
loop
    User -> Time ++ : Выбор города отправления, компании и формы оплаты
    return (результат)
end
User -> Time ++ : Переход к добавлению ДД и расходов
Time -> BusinessTrips ++ : Создание командировки в статусе черновика
return (результат)
return [[applications.time.businesstrip.creation.custom_property Страница заполнения ДД и расходов]]

deactivate User
@enduml