@startuml
'https://plantuml.com/sequence-diagram


actor User
participant "[[/architect/components/applications.time Time]]" as Time
participant "[[/architect/components/services.propertyfx PropertyFx Service]]" as PropertyFx
participant "[[/architect/components/services.vault Acis (vault)]]" as Acis
database "[[/architect/components/db.cabinet Cabinet DB]]" as Cabinet
database "[[/architect/components/db.profiles Profiles DB]]" as Profiles

activate User

loop
    User -> Time ++ : Поиск путешественника
    Time -> Profiles ++ : Запрос сотрудников
    return (результат)
    Time -> PropertyFx ++ : Получение табельных номер и департаментов
    return (результат)
    return (список сотрудников)
    User -> Time ++ : Добавление путешественника в список
    return (результат)
end
loop
    User -> Time ++ : Подтверждение списка путешественников
    Time -> Cabinet ++ : Получение компаний холдинга пользователя согласно \nнастройкам обслуживания и правам пользователя
    return (результат)
    group Включена фича set_paymentcompany_from_profilecompany
        Time -> Time : Компания, выбранная в профиле указывается предвыбранной для путешественника
    end
    group Включена фича business-trip-requisites-company-from-customproperties
        Time -> PropertyFx ++ : Получение только компаний, для которых заполнены и валидны ДД сотрудника
        return (результат)
    end
    Time -> Time : Получение форм оплат, доступных пользователю для выбранной компании
    Time -> Acis ++ : Получение доступных корп. карт
    return (результат)
    group Включена фича company-form-of-payments-override-enabled
        Time -> Time : Переопределение форм оплат
    end
    group Включена фича trip-only-profile-personal-bankCard-payment-method
        Time -> Acis ++ : Получаем и оставляем только карты, доступные сотруднику
        return (результат)
    end
    group Включена фича profile-personal-bankCard-and-other-payment-method
        Time -> Acis ++ : Получаем и оставляем только карты, доступные сотруднику
        return (результат)
        Time -> Time : Добавляем остальные формы оплаты, доступные сотруднику
    end
    return (результат)
end
loop
    User -> Time ++ : Выбор города отправления, компании и формы оплаты
    return (результат)
end
User --> Time : [[applications.time.businesstrip.creation.custom_property Переход к заполнению ДД]]

deactivate User
@enduml