@startuml
title Message1
participant "[[/architect/components/aeroclub.time Time]]" as Time
entity Queue
participant "[[/architect/components/aeroclub.feedback Feedback]]" as Feedback

activate Time
activate Queue
Time -> Queue : Message1
Queue -> Feedback ++ : Message1
Feedback -> Feedback : Process

deactivate Time
@enduml