@startuml
title Message1
participant "[[/architect/components/applications.time Time]]" as Time
entity Queue
participant "[[/architect/components/applications.integration.hub IHub]]" as IHub

activate Time
Time -> Time : **Process1**
Time -> Queue ++ : Message1
Time <-- Queue : (response)
deactivate Time
Queue -> IHub ++ : Message1
Queue <-- IHub : (response)
deactivate Queue
IHub -> IHub : **Process2**

@enduml