@startuml
title Ввод логина

actor User
participant "[[/architect/components/applications.time Time]]" as Time

User -> Time ++ : Открытие time.aero
activate User
User <-- Time : Отображение формы для ввода логина
User -> Time : Ввод и отправка логина
alt Фича automatic-redirect-to-sso включена
alt SSO настроено
User <-- Time : [[/architect/contexts/applications.time.authentication.sso Переадресация на домен пользователя]]
end alt
else
end alt
return [[/architect/contexts/applications.time.authentication.password Отображение формы для ввода пароля]]
deactivate User

@enduml