@startuml
title Ввод пароля

actor User
participant "[[/architect/components/applications.time Time]]" as Time
database "[[/architect/components/db.cabinet Cabinet]]" as Cabinet

User -> Time ++ : Ввод и отправка пароля
activate User
Time -> Cabinet ++ : Запрос аккаунта
return (результат)
Time -> Time : Валидация данных аккаунта и проверка пароля
group Включена фича limited-password-lifetime
alt Пароль старше 90 дней
User <-- Time : (сообщение об истекшем пароле)
end alt
end group
group Включена фича signin-attempts-feature
alt Введен неверный пароль более 3-х раз
Time -> Time : Блокировка аккаунта на 3 минуты
User <-- Time : (сообщение о блокировке)
end alt
end group
alt Валидация данных аккаунта и проверка пароля НЕ пройдена
User <-- Time : (ошибка)
end alt
return (результат)

deactivate User
@enduml